server:
  port: 8001

spring:
  application:
    name: myProject
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.khada.hund
  configuration:
    map-underscore-to-camel-case: true
  mvc:
    static-path-pattern: /static/**